const actionTypes = {
  GET_MOVIE_LIST_SUCCESS: 'GET_MOVIE_LIST_SUCCESS',
  GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
  ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
  UPDATE_MOVIE_SUCCESS: 'UPDATE_MOVIE_SUCCESS',
  DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
  MOVIE_API_FAILURE: 'MOVIE_API_FAILURE',
};

export default actionTypes;
